### PR TITLE
You don't need to download the android sdk

### PR DESCRIPTION
**Pull request by caboteria**
Fix the "Get the SDK" page so that it's clear that you don't download
Android.  Hopefully more of our platforms will move to this approach,
too.

### CODE REVIEW

**Comment by stevehunnicutt** [comment]
The universal email template for SDK eval has the line "
The next step is to download the SDK, which contains everything you need to emotion-enable your app or digital experience."
Do we need to decide how to address that before making this change?

**Comment by caboteria** [comment]
merged manually

**Comment by stevehunnicutt** [comment]
I'll take that as a "no". :P

**Comment by ahamino** [comment]
As a non native english speaker ..  I don't understand the difference between "download" and "install" .. coz they are used interchangeably.

**Pull request closed without merging**
