### PR TITLE
Update a couple of gems for security fixes

### PR DESCRIPTION
**Pull request by caboteria**
The little dingus on the README indicated that a couple of gems had outstanding security fixes so I updated them.

### CODE REVIEW

**Comment by BenjaminAnding** [comment]
Looks like our CI test is failing on the new nokogiri gem:
`/home/travis/build/Affectiva/developerportal/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.8/gem_make.out`

**Comment by BenjaminAnding** [comment]
looks good, i'll add abdo for one more pair of eyes on the code review

**Comment by BenjaminAnding** [comment]
thanks toby!

**Comment by caboteria** [comment]
merged manually

**Pull request closed without merging**
